name: Build feeCOMPASS apps

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'release beiing built'
        required: true
jobs:
  setup-build-gremlin-srv:
    name: Build gremlin-srv
    runs-on: ubuntu-latest

    steps:
      - name: Build started
        uses: feecompass/action-google-chat-message@v1.0.0
        with:
          message: "test build started of release ${{ github.event.inputs.version }}"
          url: ${{ secrets.CHAT_WEBHOOK_URL }}
      - name: Checkout
        uses: actions/checkout@v2
      - name:
        run: |-
          exit 1

  notify-build-success:
    name: Notify build success
    runs-on: ubuntu-latest
    if: success()
    needs: [ setup-build-gremlin-srv ]
    steps:
      # Notify on chat built success
      - name: Success message
        uses: feecompass/action-google-chat-message@v1.0.0
        with:
          message: "SUCCESS: test build of release ${{ github.event.inputs.version }}"
          url: ${{ secrets.CHAT_WEBHOOK_URL }}

  notify-build-failure:
    name: Notify build failure
    runs-on: ubuntu-latest
    if: failure()
    needs: [ setup-build-gremlin-srv ]
    steps:
      # Notify on chat built success
      - name: Success message
        uses: feecompass/action-google-chat-message@v1.0.0
        with:
          message: "FAILURE: test build of release ${{ github.event.inputs.version }}"
          url: ${{ secrets.CHAT_WEBHOOK_URL }}
