on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: simple
          package-name: release-please-action
      - name: Trigger build-feecompass workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Build feeCOMPASS apps
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          inputs: '{ "version": "${{ steps.release.outputs.tag_name }}" }'
        if: ${{ steps.release.outputs.release_created }}
